services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run alembic upgrade head &&
             poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.4-alpine3.21
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:$PGDATA

volumes:
  db-data:
