"""Initial migration

Revision ID: f0b88196deb7
Revises: 
Create Date: 2025-03-17 17:35:57.581024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b88196deb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('notes_previous_version_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'notes', ['previous_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_previous_version_id_fkey', 'notes', 'notes', ['previous_version_id'], ['id'])
    op.drop_column('notes', 'is_deleted')
    # ### end Alembic commands ###
